name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - urllib3
      - django
      - spacy
      - pymongo
      - django-ninja
      - app-store-scraper
      - google-play-scraper
      - newscatcherapi
      - selenium
      - plantuml
      - emoji
      - langdetect
      - python-dotenv
      - django-cors-headers
